server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leegive/MicroService.git
          search-paths: config-repo
          username: leegive
          password: Wj173749
